spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qgzx?serverTimezone=GMT%2B8
    username: postgres
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true
server:
  port: 8400

