spring:
  datasource:
    name: User
    url: jdbc:mysql://localhost:3306/qgzx?serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8400